/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: Hungarian *********/

/**
 * Generated by BuildLangModel.py
 * On: 2021-03-16 19:23:30.842519
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_2_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 15, 23, 16,  0, 25, 14, 20,  7, 22,  8,  4, 13,  5,  9, /* 4X */
   21, 34,  6,  3,  2, 19, 18, 32, 33, 17, 10,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 15, 23, 16,  0, 25, 14, 20,  7, 22,  8,  4, 13,  5,  9, /* 6X */
   21, 34,  6,  3,  2, 19, 18, 32, 33, 17, 10,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM, 55,SYM, 40,SYM, 56, 51,SYM,SYM, 38, 54, 57, 58,SYM, 43, 59, /* AX */
  SYM, 55,SYM, 40,SYM, 60, 51,SYM,SYM, 38, 54, 61, 62,SYM, 43, 63, /* BX */
   64, 11, 45, 41, 37, 65, 35, 50, 39, 12, 66, 46, 49, 28, 42, 67, /* CX */
   36, 52, 68, 26, 44, 27, 24,SYM, 48, 69, 30, 31, 29, 47, 70, 53, /* DX */
   71, 11, 45, 41, 37, 72, 35, 50, 39, 12, 73, 46, 49, 28, 42, 74, /* EX */
   36, 52, 75, 26, 44, 27, 24,SYM, 48, 76, 30, 31, 29, 47, 77,SYM, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1250_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 15, 23, 16,  0, 25, 14, 20,  7, 22,  8,  4, 13,  5,  9, /* 4X */
   21, 34,  6,  3,  2, 19, 18, 32, 33, 17, 10,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 15, 23, 16,  0, 25, 14, 20,  7, 22,  8,  4, 13,  5,  9, /* 6X */
   21, 34,  6,  3,  2, 19, 18, 32, 33, 17, 10,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM,ILL,SYM,SYM,SYM,SYM,ILL,SYM, 38,SYM, 51, 78, 43, 79, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,ILL,SYM, 38,SYM, 51, 80, 43, 81, /* 9X */
  SYM,SYM,SYM, 40,SYM, 55,SYM,SYM,SYM,SYM, 54,SYM,SYM,SYM,SYM, 82, /* AX */
  SYM,SYM,SYM, 40,SYM,SYM,SYM,SYM,SYM, 55, 54,SYM, 83,SYM, 84, 85, /* BX */
   86, 11, 45, 41, 37, 87, 35, 50, 39, 12, 88, 46, 49, 28, 42, 89, /* CX */
   36, 52, 90, 26, 44, 27, 24,SYM, 48, 91, 30, 31, 29, 47, 92, 53, /* DX */
   93, 11, 45, 41, 37, 94, 35, 50, 39, 12, 95, 46, 49, 28, 42, 96, /* EX */
   36, 52, 97, 26, 44, 27, 24,SYM, 48, 98, 30, 31, 29, 47, 99,SYM, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 64;
static const unsigned int Unicode_CharOrder[] =
{
   65,  1,  66, 15,  67, 23,  68, 16,  69,  0,  70, 25,  71, 14, 72, 20,
   73,  7,  74, 22,  75,  8,  76,  4,  77, 13,  78,  5,  79,  9, 80, 21,
   82,  6,  83,  3,  84,  2,  85, 19,  86, 18,  89, 17,  90, 10, 97,  1,
   98, 15,  99, 23, 100, 16, 101,  0, 102, 25, 103, 14, 104, 20,105,  7,
  106, 22, 107,  8, 108,  4, 109, 13, 110,  5, 111,  9, 112, 21,114,  6,
  115,  3, 116,  2, 117, 19, 118, 18, 121, 17, 122, 10, 193, 11,201, 12,
  205, 28, 211, 26, 214, 24, 218, 30, 220, 29, 225, 11, 233, 12,237, 28,
  243, 26, 246, 24, 250, 30, 252, 29, 336, 27, 337, 27, 368, 31,369, 31,
};


/* Model Table:
 * Total sequences: 1122
 * First 512 sequences: 0.9736098834669349
 * Next 512 sequences (512-1024): 0.026285470450181352
 * Rest: 0.00010464608288375879
 * Negative sequences: TODO
 */
static const PRUint8 HungarianLangModel[] =
{
  2,3,3,3,3,3,3,3,3,3,3,2,2,3,3,3,3,2,3,3,3,3,3,3,2,3,2,1,2,2,0,0,
  2,2,3,3,3,3,3,3,3,2,3,2,2,3,3,3,3,3,3,3,3,3,3,3,2,3,2,0,2,2,2,0,
  3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,2,3,3,3,3,2,3,2,3,2,3,3,3,3,3,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,2,2,3,3,3,2,3,2,2,3,3,3,3,3,2,
  3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,2,2,
  3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,2,3,3,3,2,3,2,2,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,2,3,3,3,3,2,3,1,3,3,1,2,2,2,2,
  3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,2,2,2,3,2,2,2,2,3,2,3,2,3,3,2,2,
  2,2,3,3,3,3,3,2,3,2,3,2,2,3,3,3,3,2,3,3,3,3,2,3,1,3,2,0,0,0,0,0,
  3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,2,2,3,2,3,3,3,3,2,2,
  2,2,3,3,3,3,3,2,3,2,3,2,2,3,3,3,3,0,3,2,2,3,3,3,0,2,0,0,2,0,0,0,
  2,2,3,3,3,3,3,2,3,2,3,0,2,3,3,3,3,0,3,0,3,3,2,2,0,2,0,0,2,2,0,0,
  3,3,3,3,3,2,2,3,2,3,3,3,3,3,2,3,2,2,2,3,2,3,2,2,2,2,3,2,3,2,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,3,3,3,2,3,2,3,3,3,2,3,3,2,2,
  3,3,2,3,3,2,3,3,2,3,2,3,3,2,0,3,2,2,2,3,2,2,2,2,3,2,3,3,2,2,2,2,
  3,3,3,3,2,3,3,3,2,3,2,3,3,3,2,2,3,2,3,3,2,2,3,2,3,2,3,3,3,2,2,2,
  3,3,3,3,3,3,2,3,2,3,3,3,3,2,2,3,2,0,3,3,2,2,2,2,2,2,3,3,3,3,2,3,
  3,3,2,2,2,2,2,3,2,3,1,3,3,2,2,2,1,2,2,2,2,2,2,2,2,2,2,3,3,2,2,2,
  2,2,3,3,3,3,3,2,3,2,2,3,0,3,3,2,3,2,2,2,2,2,2,3,0,2,2,1,1,0,0,0,
  3,3,2,2,2,2,2,3,2,3,2,3,3,2,2,2,2,2,2,3,2,2,2,2,2,2,2,2,3,2,2,2,
  3,3,3,3,3,2,3,3,2,3,2,3,3,2,2,2,2,2,2,3,2,3,3,3,2,2,2,2,3,3,2,0,
  3,3,3,2,3,3,2,2,2,3,2,3,3,2,2,2,3,2,2,3,2,2,2,2,2,2,3,1,2,2,3,2,
  3,3,2,3,2,2,2,3,3,3,2,2,3,2,2,2,2,2,2,2,3,2,2,3,2,2,2,0,3,0,0,1,
  0,0,3,3,3,3,3,0,3,0,3,0,0,2,2,3,3,0,3,0,2,2,1,2,0,2,0,0,0,0,0,0,
  3,3,2,2,2,2,3,3,2,3,0,2,3,2,2,2,2,2,1,2,1,2,2,2,3,2,2,3,1,3,2,2,
  2,2,3,3,3,3,3,3,3,2,3,2,2,2,3,3,3,1,2,2,2,3,3,3,1,2,0,0,1,2,2,0,
  3,2,3,3,3,2,3,3,3,2,3,2,2,2,2,3,3,0,3,1,2,2,3,2,2,2,0,1,2,2,2,0,
  2,2,3,2,2,3,3,0,2,0,3,0,0,3,3,2,2,0,3,0,0,2,3,2,0,0,0,0,0,0,0,0,
  0,2,3,2,3,3,2,0,3,0,3,0,0,2,3,2,2,0,2,0,2,0,2,2,0,0,0,0,0,0,0,0,
  0,2,3,2,3,3,3,2,2,0,2,0,1,1,3,2,2,0,2,0,2,2,3,2,1,2,0,0,0,0,0,0,
  2,2,2,2,2,2,3,2,2,0,2,0,0,2,2,2,2,0,3,0,2,0,2,2,0,2,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_2HungarianModel =
{
  Iso_8859_2_CharToOrderMap,
  HungarianLangModel,
  32,
  (float)0.9736098834669349,
  PR_FALSE,
  "ISO-8859-2",
  "hu"
};

const SequenceModel Windows_1250HungarianModel =
{
  Windows_1250_CharToOrderMap,
  HungarianLangModel,
  32,
  (float)0.9736098834669349,
  PR_FALSE,
  "WINDOWS-1250",
  "hu"
};

const LanguageModel HungarianModel =
{
  "hu",
  Unicode_CharOrder,
  64,
  HungarianLangModel,
  32,
  (float)0.9736098834669349,
};
