/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: Spanish *********/

/**
 * Generated by BuildLangModel.py
 * On: 2021-03-16 11:33:00.157304
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 4X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 6X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 38,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 51, 54,SYM,SYM, 51,SYM,SYM,SYM, 46, 46, 55,SYM, /* BX */
   36, 25, 43, 45, 37, 56, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* CX */
   49, 27, 44, 19, 42, 57, 34,SYM, 58, 59, 30, 60, 32, 40, 50, 61, /* DX */
   36, 25, 43, 45, 37, 62, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* EX */
   49, 27, 44, 19, 42, 63, 34,SYM, 64, 65, 30, 66, 32, 40, 50, 67, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 4X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 6X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 68,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   36, 25, 43, 45, 37, 69, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* CX */
   49, 27, 44, 19, 42, 70, 34,SYM, 71, 72, 30, 73, 32, 40, 50, 74, /* DX */
   36, 25, 43, 45, 37, 75, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* EX */
   49, 27, 44, 19, 42, 76, 34,SYM, 77, 78, 30, 79, 32, 40, 50, 80, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 4X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 20,  4, 24, 29,  7, 12,  3,  2, /* 6X */
   13, 22,  6,  5,  9, 11, 16, 31, 28, 18, 23,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 81,SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 46,ILL, 51,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 46,ILL, 51, 82, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 83,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   36, 25, 43, 45, 37, 84, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* CX */
   49, 27, 44, 19, 42, 85, 34,SYM, 86, 87, 30, 88, 32, 40, 50, 89, /* DX */
   36, 25, 43, 45, 37, 90, 53, 33, 35, 26, 48, 41, 39, 21, 47, 52, /* EX */
   49, 27, 44, 19, 42, 91, 34,SYM, 92, 93, 30, 94, 32, 40, 50, 95, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 66;
static const unsigned int Unicode_CharOrder[] =
{
   65,  1,  66, 14,  67, 10,  68,  8,  69,  0,  70, 17,  71, 15, 72, 20,
   73,  4,  74, 24,  75, 29,  76,  7,  77, 12,  78,  3,  79,  2, 80, 13,
   81, 22,  82,  6,  83,  5,  84,  9,  85, 11,  86, 16,  87, 31, 88, 28,
   89, 18,  90, 23,  97,  1,  98, 14,  99, 10, 100,  8, 101,  0,102, 17,
  103, 15, 104, 20, 105,  4, 106, 24, 107, 29, 108,  7, 109, 12,110,  3,
  111,  2, 112, 13, 113, 22, 114,  6, 115,  5, 116,  9, 117, 11,118, 16,
  119, 31, 120, 28, 121, 18, 122, 23, 193, 25, 201, 26, 205, 21,209, 27,
  211, 19, 218, 30, 220, 32, 225, 25, 233, 26, 237, 21, 241, 27,243, 19,
  250, 30, 252, 32,
};


/* Model Table:
 * Total sequences: 1002
 * First 512 sequences: 0.9966074680689881
 * Next 512 sequences (512-1024): 0.003392531931011823
 * Rest: 3.209238430557093e-17
 * Negative sequences: TODO
 */
static const PRUint8 SpanishLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,0,3,3,3,2,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,2,2,3,3,3,3,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,3,2,2,2,3,3,0,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,2,3,3,3,3,3,3,3,3,2,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,3,3,2,0,3,3,0,0,3,2,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,3,0,2,3,3,2,2,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,0,2,2,2,2,2,
  3,3,3,2,3,3,3,2,2,2,2,3,3,2,2,2,2,2,3,3,2,3,3,2,2,3,3,0,2,2,2,2,0,
  3,3,3,3,3,3,3,3,2,3,3,3,3,2,3,2,2,2,3,3,3,3,0,3,2,3,3,0,2,2,3,2,0,
  3,3,3,3,3,2,3,3,3,3,3,3,3,2,2,2,2,2,2,3,3,3,2,2,0,3,3,0,2,3,2,0,0,
  3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,2,3,3,3,3,3,3,3,2,3,0,2,0,
  3,3,3,3,3,3,3,2,2,2,3,3,3,3,3,2,2,2,3,3,2,3,0,2,2,3,3,0,2,2,3,2,2,
  3,3,3,2,3,3,3,3,2,3,3,3,2,3,2,2,2,2,2,3,3,3,2,2,0,3,3,0,0,2,3,0,0,
  3,3,3,3,3,3,3,3,3,3,2,3,2,2,3,2,2,2,2,3,2,3,0,2,3,3,3,0,0,2,2,2,2,
  3,3,3,3,3,3,3,3,2,3,2,3,2,2,2,2,0,2,3,3,3,3,0,2,0,2,3,0,2,2,3,2,3,
  3,3,3,2,3,2,2,2,2,2,2,3,0,0,2,2,2,0,2,3,2,3,0,0,0,3,3,0,0,2,0,0,0,
  3,3,3,2,3,2,3,3,2,3,2,3,2,2,2,2,0,3,2,3,0,3,0,0,0,2,3,0,0,2,3,0,0,
  3,3,3,3,3,3,2,3,2,2,2,3,2,2,2,2,2,2,2,3,2,0,0,2,2,2,2,0,2,2,2,2,0,
  2,2,0,3,2,3,3,3,3,2,3,0,3,3,2,3,3,2,2,0,2,0,2,0,2,0,0,2,2,2,0,0,0,
  3,3,3,3,3,2,3,3,2,3,2,3,3,2,2,0,0,2,3,2,2,3,2,2,0,2,2,0,2,2,3,2,2,
  2,3,3,3,0,3,3,2,3,3,3,0,3,2,2,3,2,3,0,0,0,0,2,2,2,0,2,2,2,2,0,0,0,
  0,2,0,0,2,2,2,2,0,0,0,3,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  3,3,3,2,3,2,2,2,0,3,3,3,2,2,2,3,2,0,2,3,2,2,3,3,0,3,2,0,0,2,2,2,0,
  3,3,3,2,3,2,2,2,2,2,2,3,0,2,0,0,2,0,2,3,2,2,0,0,0,2,3,0,0,2,2,2,0,
  2,2,0,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,2,0,3,0,2,2,2,0,0,2,2,2,0,0,0,
  2,3,2,3,2,3,3,3,3,3,3,2,3,3,2,3,2,2,2,2,2,0,2,2,2,0,0,2,3,0,0,0,0,
  3,3,3,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,0,3,0,2,0,0,0,2,2,0,0,0,0,0,0,
  3,3,3,0,3,2,2,2,2,3,3,2,2,3,2,2,3,2,2,2,2,2,2,0,0,2,2,0,3,0,0,2,0,
  3,3,3,2,3,3,3,3,0,2,2,3,3,2,2,2,2,0,3,2,2,2,0,2,0,2,3,0,2,2,2,2,2,
  2,3,2,3,0,3,2,3,2,3,3,0,3,2,3,0,0,2,0,0,2,0,0,2,2,0,0,2,0,0,0,0,0,
  3,3,3,2,3,2,2,2,2,2,2,2,2,2,2,0,0,0,2,2,3,0,0,2,2,2,2,0,0,2,0,2,0,
  3,0,0,2,2,0,0,2,0,2,0,0,2,2,2,2,0,2,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_15SpanishModel =
{
  Iso_8859_15_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9966074680689881,
  PR_TRUE,
  "ISO-8859-15",
  "es"
};

const SequenceModel Iso_8859_1SpanishModel =
{
  Iso_8859_1_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9966074680689881,
  PR_TRUE,
  "ISO-8859-1",
  "es"
};

const SequenceModel Windows_1252SpanishModel =
{
  Windows_1252_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9966074680689881,
  PR_TRUE,
  "WINDOWS-1252",
  "es"
};

const LanguageModel SpanishModel =
{
  "es",
  Unicode_CharOrder,
  66,
  SpanishLangModel,
  33,
  (float)0.9966074680689881,
};
