/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: German *********/

/**
 * Generated by BuildLangModel.py
 * On: 2021-03-16 01:10:34.750155
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 15, 12, 10,  0, 18, 14,  7,  2, 22, 16,  9, 13,  3, 11, /* 4X */
   17, 30,  1,  4,  6,  8, 21, 20, 28, 24, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 15, 12, 10,  0, 18, 14,  7,  2, 22, 16,  9, 13,  3, 11, /* 6X */
   17, 30,  1,  4,  6,  8, 21, 20, 28, 24, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 59,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   48, 31, 46, 42, 23, 41, 45, 36, 35, 29, 51, 40, 55, 32, 52, 47, /* CX */
   50, 37, 53, 33, 49, 58, 26,SYM, 39, 60, 38, 61, 25, 44, 54, 27, /* DX */
   48, 31, 46, 42, 23, 41, 45, 36, 35, 29, 51, 40, 55, 32, 52, 47, /* EX */
   50, 37, 53, 33, 49, 58, 26,SYM, 39, 62, 38, 63, 25, 44, 54, 57, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 15, 12, 10,  0, 18, 14,  7,  2, 22, 16,  9, 13,  3, 11, /* 4X */
   17, 30,  1,  4,  6,  8, 21, 20, 28, 24, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 15, 12, 10,  0, 18, 14,  7,  2, 22, 16,  9, 13,  3, 11, /* 6X */
   17, 30,  1,  4,  6,  8, 21, 20, 28, 24, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 64,SYM,SYM,SYM,SYM,SYM,SYM, 34,SYM, 56,ILL, 43,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 34,SYM, 56,ILL, 43, 57, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 65,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   48, 31, 46, 42, 23, 41, 45, 36, 35, 29, 51, 40, 55, 32, 52, 47, /* CX */
   50, 37, 53, 33, 49, 58, 26,SYM, 39, 66, 38, 67, 25, 44, 54, 27, /* DX */
   48, 31, 46, 42, 23, 41, 45, 36, 35, 29, 51, 40, 55, 32, 52, 47, /* EX */
   50, 37, 53, 33, 49, 58, 26,SYM, 39, 68, 38, 69, 25, 44, 54, 57, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 61;
static const unsigned int Unicode_CharOrder[] =
{
   65,  5,  66, 15,  67, 12,  68, 10,  69,  0,  70, 18,  71, 14, 72,  7,
   73,  2,  74, 22,  75, 16,  76,  9,  77, 13,  78,  3,  79, 11, 80, 17,
   81, 30,  82,  1,  83,  4,  84,  6,  85,  8,  86, 21,  87, 20, 88, 28,
   89, 24,  90, 19,  97,  5,  98, 15,  99, 12, 100, 10, 101,  0,102, 18,
  103, 14, 104,  7, 105,  2, 106, 22, 107, 16, 108,  9, 109, 13,110,  3,
  111, 11, 112, 17, 113, 30, 114,  1, 115,  4, 116,  6, 117,  8,118, 21,
  119, 20, 120, 28, 121, 24, 122, 19, 196, 23, 201, 29, 214, 26,220, 25,
  223, 27, 228, 23, 233, 29, 246, 26, 252, 25,
};


/* Model Table:
 * Total sequences: 1337
 * First 512 sequences: 0.9936565191798025
 * Next 512 sequences (512-1024): 0.00616485529057582
 * Rest: 0.00017862552962171364
 * Negative sequences: TODO
 */
static const PRUint8 GermanLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,2,3,3,0,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,0,2,3,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,0,2,3,3,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,1,2,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,0,1,3,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,0,0,3,3,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,2,3,3,3,3,0,1,2,2,
  3,3,3,3,3,3,3,2,3,3,3,3,2,3,2,3,3,2,3,2,3,2,2,3,3,3,3,0,0,2,2,
  3,3,3,3,3,3,3,3,2,3,3,2,3,3,3,3,3,3,3,3,3,3,2,1,2,1,1,3,3,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,1,0,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,2,3,2,3,2,2,3,3,2,2,0,0,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,0,0,3,3,1,2,
  3,3,3,2,2,3,3,3,3,3,2,3,3,2,2,2,3,2,2,3,2,2,2,2,3,1,1,0,0,2,2,
  3,3,3,2,3,3,3,2,3,3,3,3,3,3,2,3,3,3,3,2,2,2,2,3,3,3,3,0,1,2,0,
  3,3,3,3,3,3,3,3,3,3,2,3,2,2,3,3,3,2,2,3,3,2,2,2,3,3,2,0,1,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,3,2,2,2,2,2,2,3,3,3,3,0,0,2,0,
  3,3,3,3,3,3,3,3,3,3,2,3,2,3,2,2,3,3,2,3,3,2,2,3,3,3,3,0,2,2,0,
  3,3,3,2,3,3,3,3,3,3,3,3,2,2,2,2,2,3,3,2,2,2,2,3,2,2,2,1,0,2,1,
  3,3,3,3,3,3,3,2,3,3,2,3,2,3,3,3,2,2,3,2,2,2,2,3,2,3,2,0,0,2,1,
  3,2,3,2,3,3,3,2,3,3,2,3,2,3,2,3,2,2,2,3,3,2,2,2,3,2,3,0,0,2,2,
  3,3,3,3,3,3,2,2,3,3,2,3,2,2,2,2,2,2,2,0,2,0,3,3,2,3,2,0,0,1,0,
  3,2,3,2,2,3,2,2,2,2,2,3,2,1,2,1,2,2,2,1,2,2,0,2,2,0,3,0,0,2,0,
  3,2,3,2,2,3,2,1,3,2,2,3,2,2,1,1,2,0,1,2,0,1,2,3,2,3,2,0,0,2,0,
  2,3,3,3,3,1,3,3,3,3,3,3,3,3,3,2,2,2,3,2,0,2,0,1,1,0,0,2,0,0,2,
  3,3,3,3,3,3,3,2,2,3,3,3,3,3,2,2,3,3,2,2,2,2,2,0,2,2,2,1,1,1,0,
  2,3,1,3,3,1,3,3,0,3,3,0,3,2,3,3,2,2,2,1,1,0,0,0,0,1,0,2,1,0,0,
  2,3,2,3,3,0,3,3,0,3,2,1,2,3,2,2,2,2,3,2,2,2,0,0,1,0,1,3,1,0,0,
  3,2,3,2,2,2,3,2,2,2,2,2,0,2,2,3,2,1,2,1,2,2,0,0,0,0,0,0,0,0,0,
  3,1,3,1,2,3,3,2,2,2,1,3,2,1,1,2,2,3,2,1,2,2,0,0,2,0,0,0,2,0,1,
  2,2,1,2,2,2,2,1,0,2,2,2,2,2,2,2,2,2,1,2,0,2,2,0,0,0,0,0,0,0,2,
  1,0,2,0,0,2,1,0,3,1,0,1,0,1,1,0,0,1,0,0,1,2,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_1GermanModel =
{
  Iso_8859_1_CharToOrderMap,
  GermanLangModel,
  31,
  (float)0.9936565191798025,
  PR_TRUE,
  "ISO-8859-1",
  "de"
};

const SequenceModel Windows_1252GermanModel =
{
  Windows_1252_CharToOrderMap,
  GermanLangModel,
  31,
  (float)0.9936565191798025,
  PR_TRUE,
  "WINDOWS-1252",
  "de"
};

const LanguageModel GermanModel =
{
  "de",
  Unicode_CharOrder,
  61,
  GermanLangModel,
  31,
  (float)0.9936565191798025,
};
