/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: Irish *********/

/**
 * Generated by BuildLangModel.py
 * On: 2021-03-16 19:09:36.532691
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 4X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 6X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 35,SYM, 35,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 42, 43,SYM,SYM, 44,SYM,SYM,SYM, 45, 46, 47,SYM, /* BX */
   48, 14, 49, 50, 34, 51, 52, 36, 32, 18, 40, 53, 54, 17, 55, 39, /* CX */
   56, 37, 57, 21, 58, 59, 33,SYM, 38, 60, 20, 61, 31, 62, 63, 64, /* DX */
   65, 14, 66, 67, 34, 68, 69, 36, 32, 18, 40, 70, 71, 17, 72, 39, /* EX */
   73, 37, 74, 21, 75, 76, 33,SYM, 38, 77, 20, 78, 31, 79, 80, 81, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 4X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 6X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 82,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   83, 14, 84, 85, 34, 86, 87, 36, 32, 18, 40, 88, 89, 17, 90, 39, /* CX */
   91, 37, 92, 21, 93, 94, 33,SYM, 38, 95, 20, 96, 31, 97, 98, 99, /* DX */
  100, 14,101,102, 34,103,104, 36, 32, 18, 40,105,106, 17,107, 39, /* EX */
  108, 37,109, 21,110,111, 33,SYM, 38,112, 20,113, 31,114,115,116, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_9_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 4X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 6X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM,117,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
  118, 14,119,120, 34,121,122, 36, 32, 18, 40,123,124, 17,125, 39, /* CX */
  126, 37,127, 21,128,129, 33,SYM, 38,130, 20,131, 31,132,133,134, /* DX */
  135, 14,136,137, 34,138,139, 36, 32, 18, 40,140,141, 17,142, 39, /* EX */
  143, 37,144, 21,145,146, 33,SYM, 38,147, 20,148, 31, 41,149,150, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 4X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 16,  8, 11,  5, 19, 12,  3,  1, 27, 25,  9, 13,  2, 10, /* 6X */
   22, 30,  4,  6,  7, 15, 24, 26, 29, 23, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM,151,SYM,SYM,SYM,SYM,SYM,SYM, 35,SYM,152,ILL,153,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 35,SYM,154,ILL,155,156, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM,157,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
  158, 14,159,160, 34,161,162, 36, 32, 18, 40,163,164, 17,165, 39, /* CX */
  166, 37,167, 21,168,169, 33,SYM, 38,170, 20,171, 31,172,173,174, /* DX */
  175, 14,176,177, 34,178,179, 36, 32, 18, 40,180,181, 17,182, 39, /* EX */
  183, 37,184, 21,185,186, 33,SYM, 38,187, 20,188, 31,189,190,191, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 62;
static const unsigned int Unicode_CharOrder[] =
{
   65,  0,  66, 16,  67,  8,  68, 11,  69,  5,  70, 19,  71, 12, 72,  3,
   73,  1,  74, 27,  75, 25,  76,  9,  77, 13,  78,  2,  79, 10, 80, 22,
   81, 30,  82,  4,  83,  6,  84,  7,  85, 15,  86, 24,  87, 26, 88, 29,
   89, 23,  90, 28,  97,  0,  98, 16,  99,  8, 100, 11, 101,  5,102, 19,
  103, 12, 104,  3, 105,  1, 106, 27, 107, 25, 108,  9, 109, 13,110,  2,
  111, 10, 112, 22, 113, 30, 114,  4, 115,  6, 116,  7, 117, 15,118, 24,
  119, 26, 120, 29, 121, 23, 122, 28, 193, 14, 201, 18, 205, 17,211, 21,
  218, 20, 225, 14, 233, 18, 237, 17, 243, 21, 250, 20,
};


/* Model Table:
 * Total sequences: 707
 * First 512 sequences: 0.9976732191628278
 * Next 512 sequences (512-1024): 0.0023267808371722288
 * Rest: -3.5561831257524545e-17
 * Negative sequences: TODO
 */
static const PRUint8 IrishLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3,0,3,0,0,3,3,3,3,3,2,3,3,2,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,2,3,3,0,2,3,3,3,3,3,3,3,0,2,3,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,0,2,3,0,2,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,2,0,0,0,0,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,2,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,0,3,0,3,3,3,3,3,3,2,3,3,0,
  3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,2,3,3,0,3,0,0,
  3,3,3,3,3,3,3,3,3,3,3,0,2,3,3,3,3,3,3,2,3,3,2,3,3,3,3,2,3,0,0,
  3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,3,2,3,3,3,3,3,2,3,0,3,2,0,3,2,2,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,0,3,0,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3,0,3,3,0,3,3,3,3,3,3,2,3,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,0,3,2,0,3,0,2,0,0,
  3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,3,2,3,3,2,3,3,0,2,0,2,2,0,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,2,0,3,3,3,3,3,3,2,2,3,3,3,0,0,2,0,2,0,0,
  0,3,3,0,3,2,3,3,3,3,0,3,3,3,0,0,3,3,0,3,0,0,3,0,2,0,0,0,2,0,0,
  3,3,3,2,3,3,3,3,3,3,2,3,3,3,3,2,3,3,0,2,0,0,3,2,2,2,0,0,3,2,0,
  3,3,3,3,3,3,3,2,2,3,3,2,0,0,3,3,3,3,3,2,3,3,3,3,0,0,0,2,0,0,0,
  2,0,3,0,3,0,3,3,3,3,3,3,3,2,0,0,3,0,0,2,3,2,2,0,2,0,0,0,0,0,0,
  3,3,2,0,2,2,2,3,0,2,2,2,0,2,0,0,2,0,0,0,2,0,2,0,2,0,0,0,0,0,0,
  3,3,0,3,3,3,2,3,2,3,3,0,3,2,3,3,2,3,3,3,0,3,0,2,0,0,0,0,0,0,0,
  0,3,3,0,3,0,3,3,3,3,0,3,3,2,0,0,3,0,0,0,0,0,3,0,0,0,0,0,0,0,0,
  0,3,3,0,3,0,3,3,3,3,0,3,3,3,0,0,3,0,0,2,3,0,3,0,2,0,0,0,2,0,0,
  3,3,2,3,3,3,3,3,3,3,3,2,0,2,3,3,0,3,3,0,2,3,3,2,0,0,0,2,0,2,0,
  3,2,3,0,2,3,3,2,3,3,3,2,0,3,0,3,2,0,0,2,0,0,0,2,0,0,3,0,0,0,0,
  3,3,2,0,3,3,3,2,0,2,3,0,2,0,3,2,0,3,3,0,0,3,0,2,2,0,0,0,0,0,0,
  3,3,3,3,2,3,3,0,0,3,3,0,0,3,2,3,2,0,2,0,0,0,2,3,2,2,2,0,0,0,0,
  3,3,3,3,2,3,3,2,0,3,3,2,0,0,0,2,0,0,0,0,0,0,2,2,0,2,2,0,0,0,0,
  3,3,2,0,0,3,0,0,0,0,3,0,0,0,0,3,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,
  3,3,2,3,0,3,2,2,0,0,3,2,2,2,0,3,0,0,0,0,0,2,0,2,0,0,0,0,2,0,2,
  3,3,0,0,0,2,0,2,2,2,3,0,0,0,0,0,0,0,0,3,0,0,2,2,2,0,0,0,0,2,0,
  3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_15IrishModel =
{
  Iso_8859_15_CharToOrderMap,
  IrishLangModel,
  31,
  (float)0.9976732191628278,
  PR_TRUE,
  "ISO-8859-15",
  "ga"
};

const SequenceModel Iso_8859_1IrishModel =
{
  Iso_8859_1_CharToOrderMap,
  IrishLangModel,
  31,
  (float)0.9976732191628278,
  PR_TRUE,
  "ISO-8859-1",
  "ga"
};

const SequenceModel Iso_8859_9IrishModel =
{
  Iso_8859_9_CharToOrderMap,
  IrishLangModel,
  31,
  (float)0.9976732191628278,
  PR_TRUE,
  "ISO-8859-9",
  "ga"
};

const SequenceModel Windows_1252IrishModel =
{
  Windows_1252_CharToOrderMap,
  IrishLangModel,
  31,
  (float)0.9976732191628278,
  PR_TRUE,
  "WINDOWS-1252",
  "ga"
};

const LanguageModel IrishModel =
{
  "ga",
  Unicode_CharOrder,
  62,
  IrishLangModel,
  31,
  (float)0.9976732191628278,
};
