/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: Danish *********/

/**
 * Generated by BuildLangModel.py
 * On: 2022-12-14 17:54:15.598693
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 4X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 6X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 40,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 58, 59,SYM,SYM, 60,SYM,SYM,SYM, 61, 62, 63,SYM, /* BX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 64, 39, 50, 44, /* CX */
   35, 43, 65, 34, 46, 66, 32,SYM, 19, 67, 45, 47, 30, 54, 68, 55, /* DX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 69, 39, 50, 44, /* EX */
   35, 43, 70, 34, 46, 71, 32,SYM, 19, 72, 45, 47, 30, 54, 73, 74, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 4X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 6X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 75,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 76, 39, 50, 44, /* CX */
   35, 43, 77, 34, 46, 78, 32,SYM, 19, 79, 45, 47, 30, 54, 80, 55, /* DX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 81, 39, 50, 44, /* EX */
   35, 43, 82, 34, 46, 83, 32,SYM, 19, 84, 45, 47, 30, 54, 85, 86, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 4X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 6X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 87,SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 88,ILL, 89,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 90,ILL, 91, 92, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 93,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 94, 39, 50, 44, /* CX */
   35, 43, 95, 34, 46, 96, 32,SYM, 19, 97, 45, 47, 30, 54, 98, 55, /* DX */
   42, 33, 37, 57, 31, 21, 23, 38, 36, 28, 41, 49, 99, 39, 50, 44, /* EX */
   35, 43,100, 34, 46,101, 32,SYM, 19,102, 45, 47, 30, 54,103,104, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Ibm865_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 4X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  4, 16, 22,  7,  0, 13, 10, 18,  5, 24, 11,  8, 12,  2,  9, /* 6X */
   17, 29,  1,  6,  3, 15, 14, 25, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
   38, 30, 28, 37, 31, 42, 21, 38, 41, 49, 36, 44, 50,105, 31, 21, /* 8X */
   28, 23, 23, 46, 32,106, 47,107,108, 32, 30, 19,SYM, 19,SYM,SYM, /* 9X */
   33, 39, 34, 45, 43, 43,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* CX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* DX */
   52, 55,109, 51, 48, 48,110,111, 53,112,113,114,115, 53, 56,SYM, /* EX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 60;
static const unsigned int Unicode_CharOrder[] =
{
   65,  4,  66, 16,  67, 22,  68,  7,  69,  0,  70, 13,  71, 10, 72, 18,
   73,  5,  74, 24,  75, 11,  76,  8,  77, 12,  78,  2,  79,  9, 80, 17,
   81, 29,  82,  1,  83,  6,  84,  3,  85, 15,  86, 14,  87, 25, 88, 27,
   89, 20,  90, 26,  97,  4,  98, 16,  99, 22, 100,  7, 101,  0,102, 13,
  103, 10, 104, 18, 105,  5, 106, 24, 107, 11, 108,  8, 109, 12,110,  2,
  111,  9, 112, 17, 113, 29, 114,  1, 115,  6, 116,  3, 117, 15,118, 14,
  119, 25, 120, 27, 121, 20, 122, 26, 197, 21, 198, 23, 201, 28,216, 19,
  229, 21, 230, 23, 233, 28, 248, 19,
};


/* Model Table:
 * Total considered sequences: 1014 / 900
 * - Positive sequences: first 503 (0.9950476836368553)
 * - Probable sequences: next 175 (678-503) (0.003954982568821541)
 * - Neutral sequences: last 222 (0.0009973337943232075)
 * - Negative sequences: -114 (off-ratio)
 * Negative sequences: TODO
 */
static const PRUint8 DanishLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,2,3,2,3,3,2,3,0,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,3,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,2,2,
  3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,0,3,1,3,3,3,3,1,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,1,3,2,3,2,3,3,1,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,0,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,0,2,1,
  3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,1,2,0,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,1,3,0,3,3,3,2,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,1,3,3,2,1,0,1,0,
  3,3,3,3,3,3,3,2,3,3,2,3,3,2,3,3,2,2,3,3,3,3,2,3,3,2,2,1,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,3,0,2,0,2,3,1,
  3,3,3,3,3,3,3,2,3,3,3,2,2,3,2,3,2,2,3,3,3,3,2,3,3,0,0,2,2,1,
  3,3,3,3,3,3,3,3,3,3,2,2,2,2,1,3,2,1,2,3,2,3,1,3,3,0,0,0,1,0,
  3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,2,3,3,3,1,2,0,3,1,2,1,2,2,2,1,
  3,3,3,3,3,3,3,2,3,3,1,1,2,1,2,3,3,1,2,3,3,3,2,3,3,2,0,0,1,0,
  3,3,3,3,3,3,3,3,3,3,3,2,2,3,2,3,3,3,3,2,2,3,2,3,1,1,1,0,1,0,
  3,3,3,3,3,3,3,2,3,3,1,1,3,1,3,3,2,1,2,3,3,3,1,3,3,3,1,1,1,0,
  3,3,3,3,1,2,3,3,3,2,3,3,3,2,3,0,3,1,1,0,2,0,1,0,3,0,0,0,0,0,
  3,3,3,3,3,2,3,3,3,3,3,3,3,2,3,2,3,3,2,0,1,0,2,0,1,2,2,0,0,1,
  3,3,3,3,0,0,3,3,3,0,2,3,1,2,3,0,3,1,1,1,0,1,2,0,0,0,0,0,0,0,
  3,3,1,3,3,3,2,2,3,3,0,3,2,1,2,3,1,1,3,1,3,0,3,2,1,0,1,0,1,2,
  2,3,3,3,1,3,3,3,3,2,3,3,3,3,3,2,3,2,1,0,0,0,2,1,0,0,0,0,0,0,
  3,3,2,3,3,2,3,3,3,3,1,2,2,2,1,3,2,1,2,3,3,1,0,3,1,0,0,0,1,0,
  3,2,2,2,3,3,2,1,2,3,0,1,1,1,0,1,1,1,2,0,2,0,1,0,0,2,1,0,0,0,
  3,1,1,2,3,3,1,1,1,3,1,1,2,1,1,2,2,1,2,0,3,0,1,0,1,1,3,0,0,1,
  2,0,1,2,2,3,1,1,1,2,0,0,0,1,2,0,0,1,1,1,1,0,2,0,0,1,0,1,0,0,
  2,2,2,2,2,0,2,2,1,1,1,2,2,1,1,1,2,2,1,0,0,0,1,0,1,0,1,0,0,0,
  0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_15DanishModel =
{
  Iso_8859_15_CharToOrderMap,
  DanishLangModel,
  30,
  (float)0.9990026662056768,
  PR_TRUE,
  "ISO-8859-15",
  "da"
};

const SequenceModel Iso_8859_1DanishModel =
{
  Iso_8859_1_CharToOrderMap,
  DanishLangModel,
  30,
  (float)0.9990026662056768,
  PR_TRUE,
  "ISO-8859-1",
  "da"
};

const SequenceModel Windows_1252DanishModel =
{
  Windows_1252_CharToOrderMap,
  DanishLangModel,
  30,
  (float)0.9990026662056768,
  PR_TRUE,
  "WINDOWS-1252",
  "da"
};

const SequenceModel Ibm865DanishModel =
{
  Ibm865_CharToOrderMap,
  DanishLangModel,
  30,
  (float)0.9990026662056768,
  PR_TRUE,
  "IBM865",
  "da"
};

const LanguageModel DanishModel =
{
  "da",
  Unicode_CharOrder,
  60,
  DanishLangModel,
  30,
  4,
  (float)0.38104323327928524,
  20,
  (float)0.030308128394864135,
};
