/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsLanguageDetector.h"

/********* Language model for: Italian *********/

/**
 * Generated by BuildLangModel.py
 * On: 2022-12-14 18:09:46.154350
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 4X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 6X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 61,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* CX */
   62, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 63, 56, 52, /* DX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* EX */
   64, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 65, 56, 66, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_3_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 4X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 6X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM, 67,SYM,SYM,SYM,ILL, 68,SYM,SYM, 60, 59, 58, 69,SYM,ILL, 70, /* AX */
  SYM, 71,SYM,SYM,SYM,SYM, 72,SYM,SYM, 73, 59, 58, 74,SYM,ILL, 75, /* BX */
   21, 36, 41,ILL, 33, 76, 77, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* CX */
  ILL, 43, 23, 37, 50, 78, 32,SYM, 79, 25, 51, 55, 34, 80, 81, 52, /* DX */
   21, 36, 41,ILL, 33, 82, 83, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* EX */
  ILL, 43, 23, 37, 50, 84, 32,SYM, 85, 25, 51, 55, 34, 86, 87,SYM, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_9_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 4X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 6X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 88,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* CX */
   58, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 60, 59, 52, /* DX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* EX */
   58, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 89, 59, 90, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 4X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 6X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 40,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 45, 91,SYM,SYM, 45,SYM,SYM,SYM, 57, 57, 92,SYM, /* BX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* CX */
   93, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 94, 56, 52, /* DX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* EX */
   95, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34, 96, 56, 97, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 4X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  1, 16, 14, 19,  0, 31, 24,  5, 13,  4,  3, /* 6X */
   12, 20,  7,  8,  6, 11, 15, 28, 26, 27, 17,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 98,SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 57,ILL, 45,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 40,SYM, 57,ILL, 45, 99, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM,100,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* CX */
  101, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34,102, 56, 52, /* DX */
   21, 36, 41, 42, 33, 47, 35, 39, 22, 30, 44, 46, 29, 38, 54, 48, /* EX */
  103, 43, 23, 37, 50, 53, 32,SYM, 49, 25, 51, 55, 34,104, 56,105, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 76;
static const unsigned int Unicode_CharOrder[] =
{
   65,  2,  66, 18,  67,  9,  68, 10,  69,  1,  70, 16,  71, 14, 72, 19,
   73,  0,  74, 31,  75, 24,  76,  5,  77, 13,  78,  4,  79,  3, 80, 12,
   81, 20,  82,  7,  83,  8,  84,  6,  85, 11,  86, 15,  87, 28, 88, 26,
   89, 27,  90, 17,  97,  2,  98, 18,  99,  9, 100, 10, 101,  1,102, 16,
  103, 14, 104, 19, 105,  0, 106, 31, 107, 24, 108,  5, 109, 13,110,  4,
  111,  3, 112, 12, 113, 20, 114,  7, 115,  8, 116,  6, 117, 11,118, 15,
  119, 28, 120, 26, 121, 27, 122, 17, 192, 21, 193, 36, 196, 33,198, 35,
  200, 22, 201, 30, 204, 29, 210, 23, 211, 37, 214, 32, 217, 25,220, 34,
  224, 21, 225, 36, 228, 33, 230, 35, 232, 22, 233, 30, 236, 29,242, 23,
  243, 37, 246, 32, 249, 25, 252, 34,
};


/* Model Table:
 * Total considered sequences: 1168 / 1444
 * - Positive sequences: first 312 (0.9950294718278113)
 * - Probable sequences: next 206 (518-312) (0.003975533066303161)
 * - Neutral sequences: last 926 (0.000994995105885521)
 * - Negative sequences: 276 (off-ratio)
 * Negative sequences: TODO
 */
static const PRUint8 ItalianLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,3,3,3,2,1,0,1,2,1,0,0,0,1,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,0,0,2,2,0,3,3,2,0,0,2,0,1,0,0,0,1,
  3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,1,0,0,3,0,2,3,3,1,0,3,0,0,0,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,0,2,0,2,0,2,2,2,0,1,2,0,0,0,0,0,0,
  3,3,3,3,3,2,3,3,3,3,3,3,2,2,3,3,3,3,2,2,3,1,1,3,3,0,0,2,2,2,2,2,1,1,1,0,1,1,
  3,3,3,3,2,3,3,2,3,3,3,3,3,3,3,3,3,3,3,2,1,2,1,2,2,0,1,2,1,2,2,1,1,2,1,0,1,1,
  3,3,3,3,3,3,3,3,3,3,1,3,2,2,1,2,2,2,2,3,0,3,1,3,1,2,1,3,2,2,2,1,1,1,1,1,1,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,2,3,3,1,1,3,2,2,2,1,1,1,2,1,1,1,
  3,3,3,3,2,3,3,3,3,3,2,3,3,3,2,3,3,1,3,3,3,1,1,3,2,2,1,2,2,3,2,1,1,1,0,0,1,0,
  3,3,3,3,3,3,3,3,2,3,2,3,1,2,1,1,2,1,1,3,3,1,1,3,3,0,1,3,1,2,2,1,0,0,0,1,1,0,
  3,3,3,3,2,2,2,3,2,2,3,3,2,2,2,2,2,1,2,2,1,2,1,2,1,1,1,2,2,2,2,2,1,1,1,1,0,1,
  3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,2,1,0,1,3,2,0,2,1,2,3,1,2,0,0,0,0,1,0,
  3,3,3,3,2,3,3,3,3,3,2,3,3,2,1,1,2,1,1,3,1,1,1,2,1,1,1,1,1,2,1,1,1,1,0,2,0,1,
  3,3,3,3,2,2,2,2,3,2,2,3,3,3,1,1,1,1,3,1,0,1,1,2,1,0,1,2,1,1,2,1,1,1,2,0,1,1,
  3,3,3,3,3,3,2,3,2,2,2,3,1,2,3,1,1,1,2,3,1,0,1,2,1,1,0,2,2,1,1,1,2,1,1,0,0,1,
  3,3,3,3,1,2,1,3,2,1,1,3,0,1,1,3,1,0,1,0,0,1,1,2,1,0,0,1,0,1,1,1,1,2,0,1,1,0,
  3,3,3,3,1,3,2,3,1,1,1,3,1,1,2,0,3,1,1,1,0,1,2,1,1,1,0,1,0,0,1,1,1,0,1,1,0,0,
  3,3,3,3,1,1,1,0,1,1,1,3,1,1,1,1,0,3,1,1,1,1,1,2,1,0,0,1,1,1,0,1,0,0,1,0,1,0,
  3,3,3,3,3,3,2,3,2,2,2,3,2,1,1,1,1,0,3,1,0,1,1,1,1,2,0,2,1,2,2,1,1,1,1,0,0,1,
  3,3,3,3,2,3,2,3,2,1,2,3,1,2,1,1,1,1,1,1,0,0,1,0,1,0,0,2,1,1,3,1,1,1,1,0,1,1,
  1,0,2,0,0,1,1,1,1,0,0,3,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  1,0,0,0,1,1,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,
  1,1,1,1,1,1,1,2,2,1,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,1,1,1,3,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  3,3,3,3,2,2,2,2,2,1,0,2,1,3,1,1,1,0,1,2,0,1,0,1,2,1,0,2,1,0,1,0,2,1,1,0,0,0,
  0,0,0,0,1,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  3,2,2,2,1,1,2,0,0,2,1,1,1,1,0,3,1,0,0,1,0,0,0,0,0,1,3,0,1,0,0,0,0,0,0,0,1,0,
  2,2,3,2,2,3,2,2,2,2,2,1,2,2,2,1,1,1,2,1,0,1,1,0,1,1,1,2,1,1,0,1,0,0,1,0,1,0,
  3,3,3,3,2,2,2,1,2,1,1,1,0,1,0,0,1,1,1,2,0,0,0,0,1,0,0,1,2,0,0,0,0,1,1,0,0,0,
  0,1,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  1,2,2,2,1,2,1,2,2,1,2,0,1,1,2,1,1,1,2,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,
  2,3,3,3,1,1,1,1,1,1,1,3,1,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,1,0,0,1,
  1,0,0,0,2,1,2,1,1,1,1,0,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,
  1,1,0,0,2,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,2,1,1,2,1,1,1,0,1,1,1,0,1,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,
  0,0,0,1,1,0,1,1,0,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,2,1,0,1,1,1,1,0,1,1,0,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,
  1,0,0,0,2,1,0,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_1ItalianModel =
{
  Iso_8859_1_CharToOrderMap,
  ItalianLangModel,
  38,
  (float)0.9990050048941145,
  PR_TRUE,
  "ISO-8859-1",
  "it"
};

const SequenceModel Iso_8859_3ItalianModel =
{
  Iso_8859_3_CharToOrderMap,
  ItalianLangModel,
  38,
  (float)0.9990050048941145,
  PR_TRUE,
  "ISO-8859-3",
  "it"
};

const SequenceModel Iso_8859_9ItalianModel =
{
  Iso_8859_9_CharToOrderMap,
  ItalianLangModel,
  38,
  (float)0.9990050048941145,
  PR_TRUE,
  "ISO-8859-9",
  "it"
};

const SequenceModel Iso_8859_15ItalianModel =
{
  Iso_8859_15_CharToOrderMap,
  ItalianLangModel,
  38,
  (float)0.9990050048941145,
  PR_TRUE,
  "ISO-8859-15",
  "it"
};

const SequenceModel Windows_1252ItalianModel =
{
  Windows_1252_CharToOrderMap,
  ItalianLangModel,
  38,
  (float)0.9990050048941145,
  PR_TRUE,
  "WINDOWS-1252",
  "it"
};

const LanguageModel ItalianModel =
{
  "it",
  Unicode_CharOrder,
  76,
  ItalianLangModel,
  38,
  3,
  (float)0.3420627434224581,
  16,
  (float)0.03959671985669916,
};
